/* Student OS — all state is intentionally local to this browser. */
(() => {
  'use strict';
  const KEY = 'student-os-v1';
  const todayISO = () => new Date().toISOString().slice(0, 10);
  const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
  const seed = { theme:'light', tasks:[], notes:[], subjects:[{id:uid(),name:'Mathematics',progress:38,color:'#6256e8'},{id:uid(),name:'Computer Science',progress:64,color:'#22a879'},{id:uid(),name:'Physics',progress:22,color:'#f09a55'}], plans:[], focus:{sessions:0,minutes:0,days:{}} };
  let state = load(); let currentView = 'dashboard'; let taskFilter = 'all'; let selectedDate = todayISO(); let calendarDate = new Date();
  const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
  function load(){ try { return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}; } catch { return {...seed}; } }
  function save(){ localStorage.setItem(KEY, JSON.stringify(state)); renderAll(); }
  function esc(value=''){ return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2200); }
  function openModal(html){ $('#modalContent').innerHTML=html; $('#modalBackdrop').classList.add('open'); setTimeout(()=>$('#modalContent input, #modalContent textarea')?.focus(),30); }
  function closeModal(){ $('#modalBackdrop').classList.remove('open'); }
  function modalForm(title, fields, submitText, callback){ openModal(`<h2>${title}</h2><form id="modalForm">${fields}<div class="form-actions"><button type="button" class="secondary" id="cancelModal">Cancel</button><button class="primary">${submitText}</button></div></form>`); $('#cancelModal').onclick=closeModal; $('#modalForm').onsubmit=e=>{e.preventDefault(); callback(new FormData(e.target)); closeModal();}; }
  function navigate(view){ currentView=view; $$('.view').forEach(x=>x.classList.toggle('active',x.id===view+'View')); $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); $('#pageName').textContent=view[0].toUpperCase()+view.slice(1); $('#sidebar').classList.remove('open'); $('#backdrop').classList.remove('open'); renderAll(); window.scrollTo({top:0,behavior:'smooth'}); }
  $$('.nav-item,[data-view]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)));
  $('#openSidebar').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('open')}; $('#closeSidebar').onclick=()=>navigate(currentView); $('#backdrop').onclick=()=>navigate(currentView);
  $('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark'; save();};
  $('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`student-os-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported');};
  $('#importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state={...seed,...JSON.parse(reader.result)};save();toast('Backup restored');}catch{toast('That backup file is not valid')}};reader.readAsText(file);e.target.value='';};
  function doneTasks(){return state.tasks.filter(t=>t.done).length} function streak(){let n=0,d=new Date();while(state.focus.days[d.toISOString().slice(0,10)]||state.tasks.some(t=>t.done&&t.date===d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
  function renderDashboard(){const total=state.tasks.length,done=doneTasks(),pct=total?Math.round(done/total*100):0,s=streak();$('#dashFocus').textContent=(state.focus.days[todayISO()]||0)+'m';$('#dashTasks').textContent=`${done}/${total}`;$('#dashStreak').textContent=`${s} day${s===1?'':'s'}`;$('#sideStreak').textContent=`${s} day streak`;$('#dashProgress').textContent=(state.subjects.length?Math.round(state.subjects.reduce((a,x)=>a+x.progress,0)/state.subjects.length):0)+'%';$('#bestStreak').textContent=Math.max(s,...Object.keys(state.focus.days).map((_,i)=>i+1),0);$('#dailyPercent').textContent=pct+'%';$('#dailyDone').textContent=done;$('#dailyTotal').textContent=total;$('#dailyBar').style.width=pct+'%';$('#dailyRing').style.background=`conic-gradient(var(--accent) ${pct*3.6}deg,#eeeef5 0deg)`;$('#dailyHeadline').textContent=pct===100?'Beautifully done.':pct>50?'You’re in the flow.':'A fresh start.';const next=state.tasks.filter(t=>!t.done).slice(0,3);$('#upNext').innerHTML=next.length?next.map(t=>`<div class="next-item"><i class="next-dot"></i><div><strong>${esc(t.title)}</strong><small>${esc(t.subject||'General')} · ${t.date===todayISO()?'Today':t.date||'No date'}</small></div></div>`).join(''):'<div class="empty">Nothing queued. Enjoy the space.</div>';renderMiniChart();}
  function renderMiniChart(){const days=lastDays();const vals=days.map(x=>state.focus.days[x.iso]||0),max=Math.max(30,...vals);$('#weeklyChart').innerHTML=days.map((d,i)=>`<div class="chart-column"><div style="height:${Math.max(4,vals[i]/max*105)}px"></div><small>${d.label}</small></div>`).join('');}
  function lastDays(){return [...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return {iso:d.toISOString().slice(0,10),label:d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}})}
  function renderTasks(){const q=($('#taskSearch')?.value||'').toLowerCase();let list=state.tasks.filter(t=>(taskFilter==='all'||(taskFilter==='done'?t.done:taskFilter==='active'&&!t.done:taskFilter==='today'&&t.date===todayISO()))&&t.title.toLowerCase().includes(q));$('#taskCount').textContent=state.tasks.filter(t=>!t.done).length;$('#taskList').innerHTML=list.length?list.map(t=>`<div class="task-row ${t.done?'done':''}"><button class="check" data-check="${t.id}" aria-label="Complete task">✓</button><div class="task-info"><strong>${esc(t.title)}</strong><small>${esc(t.subject||'General')} ${t.date?'· '+t.date:''}</small></div>${t.subject?`<span class="tag">${esc(t.subject)}</span>`:''}<button class="row-delete" data-delete-task="${t.id}" aria-label="Delete task">×</button></div>`).join(''):'<div class="empty">No tasks here yet. Add one small thing to get moving.</div>';$$('[data-check]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.check);t.done=!t.done;save()});$$('[data-delete-task]').forEach(b=>b.onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==b.dataset.deleteTask);save()});}
  function renderNotes(){const q=($('#noteSearch')?.value||'').toLowerCase();const list=state.notes.filter(n=>(n.title+n.body).toLowerCase().includes(q));$('#notesGrid').innerHTML=list.length?list.map(n=>`<article class="note-card"><button class="note-delete" data-delete-note="${n.id}">×</button><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><div class="note-meta"><span>${n.date||'Today'}</span><span>Local note</span></div></article>`).join(''):'<div class="empty">No notes yet. Capture the thought while it’s here.</div>';$$('[data-delete-note]').forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(x=>x.id!==b.dataset.deleteNote);save()});}
  function renderSubjects(){ $('#subjectGrid').innerHTML=state.subjects.length?state.subjects.map(s=>`<article class="subject-card"><div class="subject-top"><h3>${esc(s.name)}</h3><strong class="subject-percent">${s.progress}%</strong></div><div class="bar"><span style="width:${s.progress}%;background:${s.color||'var(--accent)'}"></span></div><small>Progress · <button class="link-button" data-edit-subject="${s.id}">Update</button> <button class="link-button" data-delete-subject="${s.id}">Delete</button></small></article>`).join(''):'<div class="empty">Add your first subject to start tracking progress.</div>';$$('[data-edit-subject]').forEach(b=>b.onclick=()=>subjectModal(state.subjects.find(x=>x.id===b.dataset.editSubject)));$$('[data-delete-subject]').forEach(b=>b.onclick=()=>{state.subjects=state.subjects.filter(x=>x.id!==b.dataset.deleteSubject);save()});$('#subjectSummary').innerHTML=state.subjects.map(s=>`<div class="summary-row"><div class="summary-line"><b>${esc(s.name)}</b><span>${s.progress}%</span></div><div class="bar"><span style="width:${s.progress}%;background:${s.color||'var(--accent)'}"></span></div></div>`).join('');}
  function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#monthTitle').textContent=calendarDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});const first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<button class="muted-day" disabled></button>';for(let day=1;day<=last;day++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,has=state.plans.some(p=>p.date===iso);html+=`<button class="${iso===todayISO()?'today ':''}${iso===selectedDate?'selected':''}" data-date="${iso}"><b>${day}</b>${has?'<i></i>':''}</button>`}$('#calendarGrid').innerHTML=html;$$('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar();renderDayPlans()});$('#selectedDate').textContent=selectedDate===todayISO()?'Today':new Date(selectedDate+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});renderDayPlans();}
  function renderDayPlans(){const plans=state.plans.filter(p=>p.date===selectedDate);$('#dayPlans').innerHTML=plans.length?plans.map(p=>`<div class="plan-item"><input type="checkbox" ${p.done?'checked':''} data-plan-check="${p.id}"><div><strong>${esc(p.title)}</strong><small>${esc(p.time||'Anytime')} · <button class="link-button" data-delete-plan="${p.id}">remove</button></small></div></div>`).join(''):'<div class="empty">Nothing planned for this day.</div>';$$('[data-plan-check]').forEach(b=>b.onchange=()=>{state.plans.find(p=>p.id===b.dataset.planCheck).done=b.checked;save()});$$('[data-delete-plan]').forEach(b=>b.onclick=()=>{state.plans=state.plans.filter(p=>p.id!==b.dataset.deletePlan);save()});}
  function renderFocus(){const mins=state.focus.days[todayISO()]||0;$('#sessionCount').textContent=state.focus.sessions;$('#focusMinutes').textContent=mins;$('#timerDisplay').textContent=fmt(timer.seconds);$('#timerRing').style.background=`conic-gradient(var(--accent) ${(timer.total-timer.seconds)/timer.total*360}deg,#ebedf4 0deg)`;}
  function renderStats(){const days=lastDays(),vals=days.map(d=>state.focus.days[d.iso]||0);$('#chartTotal').textContent=vals.reduce((a,b)=>a+b,0)+'m';const max=Math.max(30,...vals);$('#largeBars').innerHTML=days.map((d,i)=>`<div class="large-bar-col"><div style="height:${Math.max(4,vals[i]/max*170)}px"><em>${vals[i]}m</em></div><small>${d.label}</small></div>`).join('');}
  function renderAll(){document.body.classList.toggle('dark',state.theme==='dark');$('#themeToggle').innerHTML=state.theme==='dark'?'☀ <span>Light mode</span>':'☾ <span>Dark mode</span>';renderDashboard();renderTasks();renderNotes();renderSubjects();renderCalendar();renderFocus();renderStats();}
  function taskModal(){modalForm('Add a task',`<label class="form-field">Task title<input name="title" required placeholder="e.g. Review chapter 4"></label><label class="form-field">Subject<input name="subject" placeholder="e.g. Mathematics"></label><label class="form-field">Due date<input name="date" type="date" value="${todayISO()}"></label>`,'Add task',d=>{state.tasks.unshift({id:uid(),title:d.get('title'),subject:d.get('subject'),date:d.get('date'),done:false});save();toast('Task added')})}
  function noteModal(){modalForm('New note',`<label class="form-field">Title<input name="title" required placeholder="A thought worth keeping"></label><label class="form-field">Note<textarea name="body" rows="5" required placeholder="Write freely..."></textarea></label>`,'Save note',d=>{state.notes.unshift({id:uid(),title:d.get('title'),body:d.get('body'),date:todayISO()});save();toast('Note saved')})}
  function subjectModal(subject){modalForm(subject?'Update subject':'Add subject',`<label class="form-field">Subject name<input name="name" required value="${esc(subject?.name||'')}" placeholder="e.g. Biology"></label><label class="form-field">Progress (0–100)<input name="progress" type="number" min="0" max="100" value="${subject?.progress||0}"></label>`,'Save subject',d=>{if(subject){subject.name=d.get('name');subject.progress=Number(d.get('progress'))}else state.subjects.push({id:uid(),name:d.get('name'),progress:Number(d.get('progress')),color:'#6256e8'});save();toast('Subject saved')})}
  function planModal(){modalForm('Add a plan',`<label class="form-field">What will you study?<input name="title" required placeholder="e.g. Read lecture notes"></label><label class="form-field">Date<input name="date" type="date" value="${selectedDate}"></label><label class="form-field">Time<input name="time" type="time"></label>`,'Add to planner',d=>{state.plans.push({id:uid(),title:d.get('title'),date:d.get('date'),time:d.get('time'),done:false});selectedDate=d.get('date');save();toast('Plan added')})}
  $('#addTaskBtn').onclick=taskModal;$('#addNoteBtn').onclick=noteModal;$('#addSubjectBtn').onclick=()=>subjectModal();$('#addPlanBtn').onclick=planModal;$('#quickNote').onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey))$('#saveQuick').click()};$('#saveQuick').onclick=()=>{const body=$('#quickNote').value.trim();if(!body)return toast('Write something first');state.notes.unshift({id:uid(),title:'Quick capture',body,date:todayISO()});$('#quickNote').value='';save();toast('Saved to Notes')};$('#taskSearch').oninput=renderTasks;$('#noteSearch').oninput=renderNotes;$$('#taskFilters button').forEach(b=>b.onclick=()=>{$$('#taskFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');taskFilter=b.dataset.filter;renderTasks()});$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
  let timer={seconds:1500,total:1500,interval:null};const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$$('[data-minutes]').forEach(b=>b.onclick=()=>{$$('[data-minutes]').forEach(x=>x.classList.remove('active'));b.classList.add('active');timer.seconds=timer.total=Number(b.dataset.minutes)*60;$('#timerLabel').textContent='Ready when you are';renderFocus()});$('#timerStart').onclick=()=>{if(timer.interval){clearInterval(timer.interval);timer.interval=null;$('#timerStart').textContent='Resume timer';$('#timerLabel').textContent='Paused';return}$('#timerStart').textContent='Pause timer';$('#timerLabel').textContent='Stay with it';timer.interval=setInterval(()=>{timer.seconds--;renderFocus();if(timer.seconds<=0){clearInterval(timer.interval);timer.interval=null;state.focus.sessions++;state.focus.minutes=(state.focus.minutes||0)+Math.round(timer.total/60);state.focus.days[todayISO()]=(state.focus.days[todayISO()]||0)+Math.round(timer.total/60);save();toast('Session complete — well done!');$('#timerStart').textContent='Start timer';$('#timerLabel').textContent='Session complete';timer.seconds=timer.total}},1000)};$('#timerReset').onclick=()=>{clearInterval(timer.interval);timer.interval=null;timer.seconds=timer.total;$('#timerStart').textContent='Start timer';$('#timerLabel').textContent='Ready when you are';renderFocus()};
  renderAll();
})();
